trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesServiceConnection: CostModel-DEV-uni-apps-aks-dev-ictd-oi-costmodel-dev-1684231758425
  kubernetesNamespace: ictd-oi-costmodel-dev

steps:
- task: HelmDeploy@0
  displayName: 'Delete Jupyterhub Helm Prerequisites'
  continueOnError: true
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: 'uninstall'
    arguments: 'jupyterhub'
    namespace: $(kubernetesNamespace)

- task: Kubernetes@1
  displayName: Delete resources in namespace
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: delete
    arguments: "all --all"
    namespace: $(kubernetesNamespace)


- task: Kubernetes@1
  displayName: Delete PVC in namespace
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: delete
    arguments: "pvc --all"
    namespace: $(kubernetesNamespace)
